#!/bin/bash

#-------------------------------
# Generic SLURM script  -- MPI
#-------------------------------

#SBATCH -J cgrtm0           # Job name
#SBATCH -o cgrtm0.o.%j      # Output file (%j expands to jobID)
#SBATCH -e cgrtm0.e.%j      # Error file (%j expands to jobID)
#SBATCH -p normal     # Queue name
#SBATCH -N 45              # Nodes requested
#SBATCH -n 45              # Total number of mpi tasks requested
#SBATCH -t 02:00:00        # Run time (hh:mm:ss)
#SBATCH -A TCCS            # Project account name
#SBATCH --mail-user=tharit.tangkij@utexas.edu # Email address
#SBATCH --mail-type=begin  # email me when the job starts
#SBATCH --mail-type=end    # email me when the job finishes

export OMP_NUM_THREADS=12
python cgrtm.py > out_cgrtm0.txt
